### PR TITLE
#1886 Shapes Lab Storage Error

### LINKED ISSUE #1886: Shapes Lab storage error
## Bug Report 
Shapes Lab will never start correctly if there is a category that cannot be retrieved. There is no option to reset shapes lab to mediate the problem either.
image

#### Environment
PowerPoint 2016

#### Steps to replicate
Have a category with an illegal name, (eg. `COM1`). Currently error is given whenever shapes lab is open.

#### Recommended fix
Delete the category that cause the problem.

#### Other info (Stack Trace)
System.IO.DirectoryNotFoundException
Could not find a part of the path 'C:\'.
Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheckCategorySlideToLocal(PowerPointSlide category) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 390
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.InitCategories() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 571
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.ConsistencyCheck() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 317
   at PowerPointLabs.Models.PowerPointShapeGalleryPresentation.Open(Boolean readOnly, Boolean untitled, Boolean withWindow, Boolean focus) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\Models\PowerPointShapeGalleryPresentation.cs:line 237
   at PowerPointLabs.ThisAddIn.InitializeShapeGallery() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ThisAddIn.cs:line 179
   at PowerPointLabs.ShapesLab.Views.CustomShapePaneWPF.SetStorageSettings() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ShapesLab\Views\CustomShapePaneWPF.xaml.cs:line 95
   at PowerPointLabs.ShapesLab.CustomShapePane.InitCustomShapePaneStorage() in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ShapesLab\CustomShapePane.Designer.cs:line 57
   at PowerPointLabs.ActionFramework.ShapesLab.ShapesLabActionHandler.ExecuteAction(String ribbonId) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ActionFramework\ShapesLab\ShapesLabActionHandler.cs:line 28
   at PowerPointLabs.ActionFramework.Common.Interface.ActionHandler.Execute(String ribbonId) in C:\Users\Admin\Desktop\other_repos\PowerPoint_Labs\PowerPointLabs\PowerPointLabs\ActionFramework\Common\Interface\ActionHandler.cs:line 14

### PR DESCRIPTION
**Pull request by YuPeiHenry**
Fixes #1886

Tested on PowerPoint 2016.

**Outline of Solution**
This PR adds a check for inaccessible shape categories, catches the Exception so other categories will load as per normal, and removes them permanently to prevent a recurring error.

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/Models/PowerPointShapeGalleryPresentation.cs [hunk 1]
```diff
@@ -562,13 +563,27 @@ private bool InitCategories()
             bool shapeLost = false;
             bool pngLost = false;
             int untitledCategoryCnt = 0;
+            List<int> inaccessibleCategoryIndices = new List<int>();
+            List<PowerPointSlide> slides = Slides;
 
-            foreach (PowerPointSlide category in Slides)
+            for (int i = 0; i < Slides.Count; i++)
```
Comment (ChesterSng) [inline PowerPointLabs/PowerPointLabs/Models/PowerPointShapeGalleryPresentation.cs]: You can iterate backwards instead of forwards and I think that can save the need for the `List<int> inaccessibleCategoryIndices`

By iterating backwards, you can safely delete the slide
