### PR TITLE
Blur Selected applying on wrong selection #1497

### LINKED ISSUE #1497: Blur Selected applying on wrong selection
'Blur Selected' is being applied on previous selection instead of the current selection. This bug occurs in dev-release branch (not deployed yet).

Using this pptx file: [blur-selected-bug.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/1123297/blur-selected-bug.pptx)

1. Select 'Group 14'
1. Select 'Group 6'
1. Apply 'Blur Selected' from Effects Lab

Expected result: Group 6 is blurred
Actual Result: Group 14 is blurred

### PR DESCRIPTION
**Pull request by IanTeo**
Fixes #1497 

Ensure that we are selecting the correct shape by changing the name of the shape before using it.

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+            string blurEffectSuffix = DateTime.Now.ToString("_yyyyMMddHHmmssffff_");
+
+            for (int i = 1; i <= shapeRange.Count; i++)
+            {
+                var shape = shapeRange[i];
+                if (Utils.Graphics.IsCorrupted(shape))
+                {
+                    shape = Utils.Graphics.CorruptionCorrection(shape, curSlide);
+                }
+                shape.Name = shape.Name + blurEffectSuffix;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MINOR Use a StringBuilder instead. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1643)

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+                else if (shape.Type == Office.MsoShapeType.msoPlaceholder
+                    || shape.Type == Office.MsoShapeType.msoTextBox
+                    || shape.Type == Office.MsoShapeType.msoAutoShape
+                    || shape.Type == Office.MsoShapeType.msoFreeform)
+                {
+                    ungroupedShapeNames.Add(shape.Name);
+                }
+                else
+                {
+                    throw new Exception(ErrorMessageNonShapeOrTextBox);
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MAJOR 'System.Exception' should not be thrown by user code. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS112)

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+            while (queue.Count != 0)
+            {
+                var shape = queue.Dequeue();
+
+                if (shape.Type == Office.MsoShapeType.msoGroup)
+                {
+                    var subRange = shape.Ungroup();
+                    foreach (Shape item in subRange)
+                    {
+                        item.Name = item.Name + blurEffectSuffix;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MINOR Use a StringBuilder instead. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1643)

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+                {
+                    dupSlide.Delete();
+                }
+
+                MessageBox.Show("Please select at least 1 shape");
+                return null;
+            }
+            catch (Exception e)
+            {
+                if (dupSlide != null)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MAJOR Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2583)

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+                return effectSlide;
+            }
+            catch (InvalidOperationException e)
+            {
+                MessageBox.Show(e.Message);
+                return null;
+            }
+            catch (COMException)
+            {
+                if (dupSlide != null)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MAJOR Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2583)

**Comment by initialshl** [comment]
Not sure if this bug is related to this PR:
1. Using the slide in the issue
1. Select an object inside "Group 14"
1. Apply Blur Selected
1. It does not work.

It works with child objects inside "Group 6".
Probably due to nested children.

**Comment by IanTeo** [comment]
I found the problem: We do not support blur on pictures (We have to select a shape which is placed over the image). The group has a picture inside. Seems like we have to loop through all selected objects in the group too.

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+                else if (shapeList[i].Type == Office.MsoShapeType.msoPlaceholder ||
+                    shapeList[i].Type == Office.MsoShapeType.msoTextBox ||
+                    shapeList[i].Type == Office.MsoShapeType.msoAutoShape ||
+                    shapeList[i].Type == Office.MsoShapeType.msoFreeform)
+                {
+                    ungroupedShapeNames.Add(shapeList[i].Name);
+                }
+                else
+                {
+                    throw new Exception(ErrorMessageNonShapeOrTextBox);
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MAJOR 'System.Exception' should not be thrown by user code. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS112)

File: PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs [hunk 7]
```diff
@@ -0,0 +1,156 @@
...
+                else if (originalShapeList[i].Type == Office.MsoShapeType.msoPlaceholder ||
+                    originalShapeList[i].Type == Office.MsoShapeType.msoTextBox ||
+                    originalShapeList[i].Type == Office.MsoShapeType.msoAutoShape ||
+                    originalShapeList[i].Type == Office.MsoShapeType.msoFreeform)
+                {
+                    ungroupedShapeList.Add(originalShapeList[i]);
+                }
+                else
+                {
+                    throw new Exception(ErrorMessageNonShapeOrTextBox);
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/EffectsLab/EffectsLabUtil.cs]: MAJOR 'System.Exception' should not be thrown by user code. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS112)

**Comment by initialshl** [comment]
Maybe could add tests for effects lab shapes having the same name since that was the cause of the bugs.

File: PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs [hunk 8]
```diff
@@ -261,15 +261,20 @@ public void MagnifyingGlassEffect()
...
-                var control = new RibbonControl(feature + TextCollection.DynamicMenuCheckBoxId);
-                control.Tag = TextCollection.EffectsLabBlurrinessTag;
-                Ribbon.OnCheckBoxAction(control, pressed);
-            });
+            EffectsLabBlur.IsTintSelected = isTinted;
+        }
+
+        public void SetTintForBlurRemainder(bool isTinted)
+        {
+            EffectsLabBlur.IsTintRemainder = isTinted;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

File: PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs [hunk 9]
```diff
@@ -261,15 +261,20 @@ public void MagnifyingGlassEffect()
...
+        }
+
+        public void SetTintForBlurBackground(bool isTinted)
+        {
+            EffectsLabBlur.IsTintBackground = isTinted;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

File: PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs [hunk 10]
```diff
@@ -261,15 +261,20 @@ public void MagnifyingGlassEffect()
...
+
+        public void SetTintForBlurSelected(bool isTinted)
         {
-            UIThreadExecutor.Execute(() =>
-            {
-                var control = new RibbonControl(feature + TextCollection.DynamicMenuCheckBoxId);
-                control.Tag = TextCollection.EffectsLabBlurrinessTag;
-                Ribbon.OnCheckBoxAction(control, pressed);
-            });
+            EffectsLabBlur.IsTintSelected = isTinted;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/FunctionalTestInterface.Impl/PowerPointLabsFeatures.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

**Comment by IanTeo** [comment]
Blur and recolor should work for valid items in a group now.
As a side effect, crop also works (because blur uses crop)
