### PR TITLE
#2008 Improve UI Dark Theme

### LINKED ISSUE #2008: Improve UI appearance when using Dark Theme
## Bug Report  

While most of PowerPointLabs is usable when used with the Dark Theme in PowerPoint, some parts are still hard to use such as:

- When typing in a TextBox, the Caret is still Black

image

- The Checks in Checkboxes are hard to see. In SyncLab, this the Checks are not visible at all unless the mouse is hovering over them.

image

image

- The image previews in SyncLab are still in Black. (Refer to previous screenshot)
- When hovering over a Button, the text becomes hard to see.

image

 
#### Environment (e.g. version of Microsoft PowerPoint)

Windows 10, Office 365

### PR DESCRIPTION
**Pull request by xantho09**
Fixes #2008 

**Outline of Solution**

This PR completely reworks the way Themes are handled. The goal is to have the appearance of the Dark themes (i.e. "Black" or "Dark Gray") be as good as the standard theme (i.e. "Colorful").

Normal WPF applications will have dynamic themes by updating the resources of `App.xaml` during runtime. Since this project has no such file, the next best thing I found was to update the `Resources` of the WPF elements.

Here, a theme is a `ResourceDictionary` consists of two main parts:
- A dictionary of styles for WPF controls (e.g. `Button`, `TextBlock`, etc.) 
The colours (e.g. Background, Foreground, etc.) of these styles are obtained via `DynamicResource`s. This dictionary, `TemplateStyles.xaml`, is used throughout all the themes.
- A dictionary of colours that are specific to the theme. (e.g. `BlackColors.xaml`, `ColorfulColors.xaml`)

Whenever the user changes the Color Theme of PPT, the `ApplyTheme` method will go to the `Resources` of any View subscribed to the `ColorThemeChanged` event (such as Windows or Lab Panes) and replace the existing theme resource dictionary with a new one corresponding to the new theme.

In addition, for any View that uses the MahApps styles, it will be updated to MahApps' `BaseLight.xaml` or `BaseDark.xaml` theme depending on the new Color Theme.

Finally, the View can implement the `INotifyOnThemeChanged` interface if there are any changes specific to that View that need to be made.

While there are a lot of additions in this PR, most of them are simply ResourceDictionaries containing theme-specific colours, or template styles for Controls.

**Additional Notes**

There are a few improvements that can be made:
1. Some Controls still do not have theme-specific styles, such as the `ComboBox` and `ScrollBar`.
1. Some images, such as the ones used by PositionsLab or ResizeLab, have lines that are hard to see in a Dark Theme. While it can be temporarily fixed by having the image buttons' background remain light, a better solution may be to create Dark Theme versions of those images.
1. The NarrationsLab pane is not a WPF pane, and hence, does not work with this solution. The elements in that pane still maintain the same colours when changing Color Themes. It might be a good idea to convert that into a WPF pane in a future PR.

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/ColorTheme/ThemeManager.cs [hunk 1]
```diff
@@ -74,16 +74,8 @@ private ThemeManager()
...
-                return new List<int>() { ColorTheme.COLORFUL };
-            }
-            return new List<int>()
-            {
-                ColorTheme.WHITE,
-                ColorTheme.LIGHT_GRAY,
-                ColorTheme.DARK_GRAY
-            };
+            // Have no default keys so that ApplyTheme() will always get called.
+            return new List<int>();
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/ColorTheme/ThemeManager.cs]: could this be done by removing the need to check against default keys rather than checking against an always empty list?

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/BaseBlackColors.xaml [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+    <SolidColorBrush x:Key="Theme.PaneBackgroundBrush" Color="{StaticResource Theme.PaneBackground}"/>
+
+    <SolidColorBrush x:Key="Theme.BackgroundBrush1" Color="{StaticResource Theme.Background1}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush2" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush3" Color="{StaticResource Theme.Background3}"/>
+
+    <SolidColorBrush x:Key="Theme.ForegroundBrush" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/BaseBlackColors.xaml:21]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/BlackColors.xaml [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+        <ResourceDictionary Source="LabelColors.xaml"/>
+        <ResourceDictionary Source="HyperlinkColors.xaml"/>
+        <ResourceDictionary Source="TextBlockColors.xaml"/>
+        <ResourceDictionary Source="TextBoxColors.xaml"/>
+        <ResourceDictionary Source="ToolTipColors.xaml"/>
+        <ResourceDictionary Source="TreeViewColors.xaml"/>
+        <ResourceDictionary Source="WindowColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/BlackColors.xaml:18]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/ButtonColors.xaml [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+    <SolidColorBrush x:Key="Button.Static.Foreground" Color="#FFFFFFFF"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Background" Color="#FF444444"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Border" Color="#FF969696"/>
+    <SolidColorBrush x:Key="Button.Pressed.Background" Color="#FF6A6A6A"/>
+    <SolidColorBrush x:Key="Button.Pressed.Border" Color="#FF969696"/>
+    <SolidColorBrush x:Key="Button.Disabled.Background" Color="#FF252525"/>
+    <SolidColorBrush x:Key="Button.Disabled.Border" Color="#FF444444"/>
+    <SolidColorBrush x:Key="Button.Disabled.Foreground" Color="#FF495A52"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/ButtonColors.xaml:15]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/CheckBoxColors.xaml [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+    <SolidColorBrush x:Key="OptionMark.Disabled.Border" Color="#FF444444"/>
+    <SolidColorBrush x:Key="OptionMark.Disabled.Glyph" Color="#FF444444"/>
+    
+    <SolidColorBrush x:Key="OptionMark.Pressed.Background" Color="#FFAEAEAE"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Border" Color="#FFAEAEAE"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Glyph" Color="#FFFFFFFF"/>
+    
+    <SolidColorBrush x:Key="CheckBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/CheckBoxColors.xaml:26]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/HyperlinkColors.xaml [hunk 6]
```diff
@@ -0,0 +1,8 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Hyperlink.Static.Foreground" Color="#3CA4FF"/>
+    <SolidColorBrush x:Key="Hyperlink.MouseOver.Foreground" Color="#FF378AD4"/>
+    <SolidColorBrush x:Key="Hyperlink.Disabled.Foreground" Color="#FFAAAAAA"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/HyperlinkColors.xaml:8]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/LabelColors.xaml [hunk 7]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseBlackColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="Label.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/LabelColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TextBlockColors.xaml [hunk 8]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseBlackColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TextBlock.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TextBlockColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TextBoxColors.xaml [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+
+    <SolidColorBrush x:Key="TextBox.Static.Background" Color="#FF444444"/>
+    <SolidColorBrush x:Key="TextBox.Static.Border" Color="#FF686868"/>
+    <SolidColorBrush x:Key="TextBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.Static.CaretBrush" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Background" Color="#FF333337"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Border" Color="#FFB5B5B5"/>
+    <SolidColorBrush x:Key="TextBox.Focus.Border" Color="#FF569DE5"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TextBoxColors.xaml:16]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/ToolTipColors.xaml [hunk 10]
```diff
@@ -0,0 +1,12 @@
...
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseBlackColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="ToolTip.Static.Background" Color="#FF424245"/>
+    <SolidColorBrush x:Key="ToolTip.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="ToolTip.Static.BorderBrush" Color="#FF4D4D50"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/ToolTipColors.xaml:12]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TreeViewColors.xaml [hunk 11]
```diff
@@ -0,0 +1,11 @@
...
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseBlackColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TreeView.Static.Background" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="TreeView.Static.Border" Color="#FF828790"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/TreeViewColors.xaml:11]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Black/WindowColors.xaml [hunk 12]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseBlackColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="Window.Static.Background" Color="{StaticResource Theme.Background1}"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Black/WindowColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/BlackTheme.xaml [hunk 13]
```diff
@@ -0,0 +1,9 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="Black/BlackColors.xaml"/>
+        <ResourceDictionary Source="TemplateStyles.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/BlackTheme.xaml:9]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/BaseColorfulColors.xaml [hunk 14]
```diff
@@ -0,0 +1,21 @@
...
+
+    <SolidColorBrush x:Key="Theme.PaneBackgroundBrush" Color="{StaticResource Theme.PaneBackground}"/>
+
+    <SolidColorBrush x:Key="Theme.BackgroundBrush1" Color="{StaticResource Theme.Background1}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush2" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush3" Color="{StaticResource Theme.Background3}"/>
+
+    <SolidColorBrush x:Key="Theme.ForegroundBrush" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/BaseColorfulColors.xaml:21]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ButtonColors.xaml [hunk 15]
```diff
@@ -0,0 +1,15 @@
...
+    <SolidColorBrush x:Key="Button.Static.Foreground" Color="#FF000000"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Background" Color="#FFFDC9B5"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Border" Color="#FFE86E58"/>
+    <SolidColorBrush x:Key="Button.Pressed.Background" Color="#FFED9583"/>
+    <SolidColorBrush x:Key="Button.Pressed.Border" Color="#FFC75033"/>
+    <SolidColorBrush x:Key="Button.Disabled.Background" Color="#FFFDFDFD"/>
+    <SolidColorBrush x:Key="Button.Disabled.Border" Color="#FFE1E1E1"/>
+    <SolidColorBrush x:Key="Button.Disabled.Foreground" Color="#FFCCB1BF"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ButtonColors.xaml:15]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/CheckBoxColors.xaml [hunk 16]
```diff
@@ -0,0 +1,26 @@
...
+    <SolidColorBrush x:Key="OptionMark.Disabled.Border" Color="#FFC6C6C6"/>
+    <SolidColorBrush x:Key="OptionMark.Disabled.Glyph" Color="#FFC6C6C6"/>
+    
+    <SolidColorBrush x:Key="OptionMark.Pressed.Background" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Border" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Glyph" Color="#FF000000"/>
+    
+    <SolidColorBrush x:Key="CheckBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/CheckBoxColors.xaml:26]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ColorfulColors.xaml [hunk 17]
```diff
@@ -0,0 +1,18 @@
...
+        <ResourceDictionary Source="HyperlinkColors.xaml"/>
+        <ResourceDictionary Source="LabelColors.xaml"/>
+        <ResourceDictionary Source="TextBlockColors.xaml"/>
+        <ResourceDictionary Source="TextBoxColors.xaml"/>
+        <ResourceDictionary Source="ToolTipColors.xaml"/>
+        <ResourceDictionary Source="TreeViewColors.xaml"/>
+        <ResourceDictionary Source="WindowColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ColorfulColors.xaml:18]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/HyperlinkColors.xaml [hunk 18]
```diff
@@ -0,0 +1,8 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Hyperlink.Static.Foreground" Color="#FF0000FF"/>
+    <SolidColorBrush x:Key="Hyperlink.MouseOver.Foreground" Color="#FFFF0000"/>
+    <SolidColorBrush x:Key="Hyperlink.Disabled.Foreground" Color="#FFAAAAAA"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/HyperlinkColors.xaml:8]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/LabelColors.xaml [hunk 19]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseColorfulColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+    
+    <SolidColorBrush x:Key="Label.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/LabelColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TextBlockColors.xaml [hunk 20]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseColorfulColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TextBlock.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TextBlockColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TextBoxColors.xaml [hunk 21]
```diff
@@ -0,0 +1,16 @@
...
+
+    <SolidColorBrush x:Key="TextBox.Static.Background" Color="White"/>
+    <SolidColorBrush x:Key="TextBox.Static.Border" Color="#FFABABAB"/>
+    <SolidColorBrush x:Key="TextBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.Static.CaretBrush" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Background" Color="White"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Border" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="TextBox.Focus.Border" Color="#FFDC5939"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TextBoxColors.xaml:16]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ToolTipColors.xaml [hunk 22]
```diff
@@ -0,0 +1,12 @@
...
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseColorfulColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="ToolTip.Static.Background" Color="#FFFFFFFF"/>
+    <SolidColorBrush x:Key="ToolTip.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="ToolTip.Static.BorderBrush" Color="#FFBEBEBE"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/ToolTipColors.xaml:12]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TreeViewColors.xaml [hunk 23]
```diff
@@ -0,0 +1,7 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="TreeView.Static.Background" Color="White"/>
+    <SolidColorBrush x:Key="TreeView.Static.Border" Color="#FFABABAB"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/TreeViewColors.xaml:7]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/WindowColors.xaml [hunk 24]
```diff
@@ -0,0 +1,6 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Window.Static.Background" Color="White"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/Colorful/WindowColors.xaml:6]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/ColorfulTheme.xaml [hunk 25]
```diff
@@ -0,0 +1,9 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="Colorful/ColorfulColors.xaml"/>
+        <ResourceDictionary Source="TemplateStyles.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/ColorfulTheme.xaml:9]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/BaseDarkGrayColors.xaml [hunk 26]
```diff
@@ -0,0 +1,21 @@
...
+
+    <SolidColorBrush x:Key="Theme.PaneBackgroundBrush" Color="{StaticResource Theme.PaneBackground}"/>
+
+    <SolidColorBrush x:Key="Theme.BackgroundBrush1" Color="{StaticResource Theme.Background1}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush2" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush3" Color="{StaticResource Theme.Background3}"/>
+
+    <SolidColorBrush x:Key="Theme.ForegroundBrush" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/BaseDarkGrayColors.xaml:21]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/ButtonColors.xaml [hunk 27]
```diff
@@ -0,0 +1,15 @@
...
+    <SolidColorBrush x:Key="Button.Static.Foreground" Color="#FFFFFFFF"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Background" Color="#FF363636"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Border" Color="#FFB1B1B1"/>
+    <SolidColorBrush x:Key="Button.Pressed.Background" Color="#FF262626"/>
+    <SolidColorBrush x:Key="Button.Pressed.Border" Color="#FF262626"/>
+    <SolidColorBrush x:Key="Button.Disabled.Background" Color="#FF252525"/>
+    <SolidColorBrush x:Key="Button.Disabled.Border" Color="#FF444444"/>
+    <SolidColorBrush x:Key="Button.Disabled.Foreground" Color="#FF495A52"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/ButtonColors.xaml:15]: missing newline

**Comment by xantho09** [comment]
Yeah, it's probably a good idea to add a few tests. I'll go do that.

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/CheckBoxColors.xaml [hunk 28]
```diff
@@ -0,0 +1,26 @@
...
+    <SolidColorBrush x:Key="OptionMark.Disabled.Border" Color="#FF444444"/>
+    <SolidColorBrush x:Key="OptionMark.Disabled.Glyph" Color="#FF444444"/>
+    
+    <SolidColorBrush x:Key="OptionMark.Pressed.Background" Color="#FFB83B1D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Border" Color="#FFB83B1D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Glyph" Color="#FFF0F0F0"/>
+    
+    <SolidColorBrush x:Key="CheckBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/CheckBoxColors.xaml:26]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/DarkGrayColors.xaml [hunk 29]
```diff
@@ -0,0 +1,18 @@
...
+        <ResourceDictionary Source="HyperlinkColors.xaml"/>
+        <ResourceDictionary Source="LabelColors.xaml"/>
+        <ResourceDictionary Source="TextBlockColors.xaml"/>
+        <ResourceDictionary Source="TextBoxColors.xaml"/>
+        <ResourceDictionary Source="ToolTipColors.xaml"/>
+        <ResourceDictionary Source="TreeViewColors.xaml"/>
+        <ResourceDictionary Source="WindowColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/DarkGrayColors.xaml:18]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/HyperlinkColors.xaml [hunk 30]
```diff
@@ -0,0 +1,8 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Hyperlink.Static.Foreground" Color="#FF93CDFF"/>
+    <SolidColorBrush x:Key="Hyperlink.MouseOver.Foreground" Color="#FF378AD4"/>
+    <SolidColorBrush x:Key="Hyperlink.Disabled.Foreground" Color="#FFAAAAAA"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/HyperlinkColors.xaml:8]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/LabelColors.xaml [hunk 31]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseDarkGrayColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="Label.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/LabelColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TextBlockColors.xaml [hunk 32]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseDarkGrayColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TextBlock.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TextBlockColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TextBoxColors.xaml [hunk 33]
```diff
@@ -0,0 +1,16 @@
...
+
+    <SolidColorBrush x:Key="TextBox.Static.Background" Color="#FF444444"/>
+    <SolidColorBrush x:Key="TextBox.Static.Border" Color="#FF686868"/>
+    <SolidColorBrush x:Key="TextBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.Static.CaretBrush" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Background" Color="#FF333337"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Border" Color="#FFB5B5B5"/>
+    <SolidColorBrush x:Key="TextBox.Focus.Border" Color="#FF569DE5"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TextBoxColors.xaml:16]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/ToolTipColors.xaml [hunk 34]
```diff
@@ -0,0 +1,12 @@
...
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseDarkGrayColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="ToolTip.Static.Background" Color="#FFF0F0F0"/>
+    <SolidColorBrush x:Key="ToolTip.Static.Foreground" Color="#FF000000"/>
+    <SolidColorBrush x:Key="ToolTip.Static.BorderBrush" Color="#FFBEBEBE"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/ToolTipColors.xaml:12]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TreeViewColors.xaml [hunk 35]
```diff
@@ -0,0 +1,11 @@
...
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseDarkGrayColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TreeView.Static.Background" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="TreeView.Static.Border" Color="#FF828790"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/TreeViewColors.xaml:11]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/WindowColors.xaml [hunk 36]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseDarkGrayColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="Window.Static.Background" Color="{StaticResource Theme.Background1}"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGray/WindowColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGrayTheme.xaml [hunk 37]
```diff
@@ -0,0 +1,9 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="DarkGray/DarkGrayColors.xaml"/>
+        <ResourceDictionary Source="TemplateStyles.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/DarkGrayTheme.xaml:9]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles.xaml [hunk 38]
```diff
@@ -0,0 +1,23 @@
...
+        <ResourceDictionary Source="TemplateStyles/HyperlinkStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/LabelStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/TextBlockStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/TextBoxStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/ToolTipStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/TreeViewStyle.xaml"/>
+        <ResourceDictionary Source="TemplateStyles/WindowStyle.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles.xaml:23]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/ButtonStyle.xaml [hunk 39]
```diff
@@ -0,0 +1,67 @@
...
+                </ControlTemplate>
+            </Setter.Value>
+        </Setter>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all Buttons by default. -->
+    <Style TargetType="{x:Type Button}"
+           BasedOn="{StaticResource BaseButtonStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/ButtonStyle.xaml:67]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/CheckBoxStyle.xaml [hunk 40]
```diff
@@ -0,0 +1,94 @@
...
+                </ControlTemplate>
+            </Setter.Value>
+        </Setter>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all CheckBoxes by default. -->
+    <Style TargetType="{x:Type CheckBox}"
+           BasedOn="{StaticResource BaseCheckBoxStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/CheckBoxStyle.xaml:94]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TextBlockStyle.xaml [hunk 41]
```diff
@@ -0,0 +1,19 @@
...
+    <Style TargetType="{x:Type TextBlock}"
+           x:Key="BaseTextBlockStyle">
+        <Setter Property="Foreground" Value="{DynamicResource TextBlock.Static.Foreground}"/>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all TextBlocks by default. -->
+    <Style TargetType="{x:Type TextBlock}"
+           BasedOn="{StaticResource BaseTextBlockStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TextBlockStyle.xaml:19]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TextBoxStyle.xaml [hunk 42]
```diff
@@ -0,0 +1,47 @@
...
+                </ControlTemplate>
+            </Setter.Value>
+        </Setter>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all TextBoxes by default. -->
+    <Style TargetType="{x:Type TextBox}"
+           BasedOn="{StaticResource BaseTextBoxStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TextBoxStyle.xaml:47]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/ToolTipStyle.xaml [hunk 43]
```diff
@@ -0,0 +1,31 @@
...
+        <Setter Property="Foreground" Value="{DynamicResource ToolTip.Static.Foreground}"/>
+        <Setter Property="Background" Value="{DynamicResource ToolTip.Static.Background}"/>
+        <Setter Property="BorderBrush" Value="{DynamicResource ToolTip.Static.BorderBrush}"/>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all TextBlocks by default. -->
+    <Style TargetType="{x:Type ToolTip}"
+           BasedOn="{StaticResource BaseToolTipStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/ToolTipStyle.xaml:31]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TreeViewStyle.xaml [hunk 44]
```diff
@@ -0,0 +1,21 @@
...
+           x:Key="BaseTreeViewStyle">
+        <Setter Property="Background" Value="{DynamicResource TreeView.Static.Background}"/>
+        <Setter Property="BorderBrush" Value="{DynamicResource TreeView.Static.Border}"/>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all TreeViews by default. -->
+    <Style TargetType="{x:Type TreeView}"
+           BasedOn="{StaticResource BaseTreeViewStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/TreeViewStyle.xaml:21]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/WindowStyle.xaml [hunk 45]
```diff
@@ -0,0 +1,19 @@
...
+    <Style TargetType="{x:Type Window}"
+           x:Key="BaseWindowStyle">
+        <Setter Property="Background" Value="{DynamicResource Window.Static.Background}"/>
+    </Style>
+
+    <!-- This Style has no Key, so it will be applied to all Windows by default. -->
+    <Style TargetType="{x:Type Window}"
+           BasedOn="{StaticResource BaseWindowStyle}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/TemplateStyles/WindowStyle.xaml:19]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/BaseWhiteColors.xaml [hunk 46]
```diff
@@ -0,0 +1,21 @@
...
+
+    <SolidColorBrush x:Key="Theme.PaneBackgroundBrush" Color="{StaticResource Theme.PaneBackground}"/>
+
+    <SolidColorBrush x:Key="Theme.BackgroundBrush1" Color="{StaticResource Theme.Background1}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush2" Color="{StaticResource Theme.Background2}"/>
+    <SolidColorBrush x:Key="Theme.BackgroundBrush3" Color="{StaticResource Theme.Background3}"/>
+
+    <SolidColorBrush x:Key="Theme.ForegroundBrush" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/BaseWhiteColors.xaml:21]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/ButtonColors.xaml [hunk 47]
```diff
@@ -0,0 +1,16 @@
...
+    <SolidColorBrush x:Key="Button.Static.Foreground" Color="#FF252525"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Background" Color="#FFFCE4DC"/>
+    <SolidColorBrush x:Key="Button.MouseOver.Border" Color="#FF969696"/>
+    <SolidColorBrush x:Key="Button.Pressed.Background" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="Button.Pressed.Border" Color="#FF2C628B"/>
+    <SolidColorBrush x:Key="Button.Disabled.Background" Color="#FFF4F4F4"/>
+    <SolidColorBrush x:Key="Button.Disabled.Border" Color="#FFADB2B5"/>
+    <SolidColorBrush x:Key="Button.Disabled.Foreground" Color="#FF838383"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/ButtonColors.xaml:15]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/CheckBoxColors.xaml [hunk 48]
```diff
@@ -0,0 +1,26 @@
...
+    <SolidColorBrush x:Key="OptionMark.Disabled.Border" Color="#FFC6C6C6"/>
+    <SolidColorBrush x:Key="OptionMark.Disabled.Glyph" Color="#FFC6C6C6"/>
+    
+    <SolidColorBrush x:Key="OptionMark.Pressed.Background" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Border" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="OptionMark.Pressed.Glyph" Color="#FF000000"/>
+    
+    <SolidColorBrush x:Key="CheckBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/CheckBoxColors.xaml:26]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/HyperlinkColors.xaml [hunk 49]
```diff
@@ -0,0 +1,8 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Hyperlink.Static.Foreground" Color="#FF0000FF"/>
+    <SolidColorBrush x:Key="Hyperlink.MouseOver.Foreground" Color="#FFFF0000"/>
+    <SolidColorBrush x:Key="Hyperlink.Disabled.Foreground" Color="#FFAAAAAA"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/HyperlinkColors.xaml:8]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/LabelColors.xaml [hunk 50]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseWhiteColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="Label.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/LabelColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/TextBlockColors.xaml [hunk 51]
```diff
@@ -0,0 +1,10 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseWhiteColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="TextBlock.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/TextBlockColors.xaml:10]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/TextBoxColors.xaml [hunk 52]
```diff
@@ -0,0 +1,16 @@
...
+
+    <SolidColorBrush x:Key="TextBox.Static.Background" Color="White"/>
+    <SolidColorBrush x:Key="TextBox.Static.Border" Color="#FFABABAB"/>
+    <SolidColorBrush x:Key="TextBox.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.Static.CaretBrush" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Background" Color="White"/>
+    <SolidColorBrush x:Key="TextBox.MouseOver.Border" Color="#FFF5BA9D"/>
+    <SolidColorBrush x:Key="TextBox.Focus.Border" Color="#FFDC5939"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/TextBoxColors.xaml:16]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/ToolTipColors.xaml [hunk 53]
```diff
@@ -0,0 +1,12 @@
...
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="BaseWhiteColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+    <SolidColorBrush x:Key="ToolTip.Static.Background" Color="#FFFFFFFF"/>
+    <SolidColorBrush x:Key="ToolTip.Static.Foreground" Color="{StaticResource Theme.Foreground}"/>
+    <SolidColorBrush x:Key="ToolTip.Static.BorderBrush" Color="#FFBEBEBE"/>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/ToolTipColors.xaml:12]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/TreeViewColors.xaml [hunk 54]
```diff
@@ -0,0 +1,7 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="TreeView.Static.Background" Color="White"/>
+    <SolidColorBrush x:Key="TreeView.Static.Border" Color="#FFABABAB"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/TreeViewColors.xaml:7]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/WhiteColors.xaml [hunk 55]
```diff
@@ -0,0 +1,18 @@
...
+        <ResourceDictionary Source="HyperlinkColors.xaml"/>
+        <ResourceDictionary Source="LabelColors.xaml"/>
+        <ResourceDictionary Source="TextBlockColors.xaml"/>
+        <ResourceDictionary Source="TextBoxColors.xaml"/>
+        <ResourceDictionary Source="ToolTipColors.xaml"/>
+        <ResourceDictionary Source="TreeViewColors.xaml"/>
+        <ResourceDictionary Source="WindowColors.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/WhiteColors.xaml:18]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/White/WindowColors.xaml [hunk 56]
```diff
@@ -0,0 +1,6 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <SolidColorBrush x:Key="Window.Static.Background" Color="White"/>
+    
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/White/WindowColors.xaml:6]: missing newline

File: PowerPointLabs/PowerPointLabs/Resources/Themes/WhiteTHeme.xaml [hunk 57]
```diff
@@ -0,0 +1,9 @@
+﻿<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
+                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
+
+    <ResourceDictionary.MergedDictionaries>
+        <ResourceDictionary Source="White/WhiteColors.xaml"/>
+        <ResourceDictionary Source="TemplateStyles.xaml"/>
+    </ResourceDictionary.MergedDictionaries>
+
+</ResourceDictionary>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/Resources/Themes/WhiteTHeme.xaml:9]: missing newline

File: PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatListItem.xaml [hunk 58]
```diff
@@ -5,11 +5,44 @@
...
+                           Margin="5,0" 
+                           Padding="0"
+                           MinHeight="34"
+                           HorizontalAlignment="Left" 
+                           VerticalAlignment="Center"
+                           VerticalContentAlignment="Center"/>
+            </Grid>
+        </CheckBox.Content>
+    </CheckBox>
+</UserControl>
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs/SyncLab/Views/SyncFormatListItem.xaml:48]: missing newline

File: PowerPointLabs/PowerPointLabs.sln [hunk 59]
```diff
@@ -1,34 +1,34 @@
...
-		{573CC738-5349-4A0D-BC53-9325FA9C0E6F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
-		{573CC738-5349-4A0D-BC53-9325FA9C0E6F}.Debug|Any CPU.Build.0 = Debug|Any CPU
-		{573CC738-5349-4A0D-BC53-9325FA9C0E6F}.Release|Any CPU.ActiveCfg = Release|Any CPU
-		{573CC738-5349-4A0D-BC53-9325FA9C0E6F}.Release|Any CPU.Build.0 = Release|Any CPU
-	EndGlobalSection
-	GlobalSection(SolutionProperties) = preSolution
-		HideSolutionNode = FALSE
-	EndGlobalSection
-EndGlobal
+﻿
```
Comment (iskandarzulkarnaien) [inline PowerPointLabs/PowerPointLabs.sln]: Doesn't seem to be any changes in this file

**Comment by xantho09** [comment]
@YuPeiHenry Oh wow, Blue and Silver. I'll have to take a look at their ColorThemeIDs and respective colours.

That said, from the screenshot, it seems like the external window did respond to the color theme:
- The Blue and Silver themes were probably not recognized in the list of themes in the code (Colorful, Black, Dark Gray and White), so the code defaults it to the Colorful theme. (Or it was `LIGHT_GRAY` or `DARK_GRAY_ALT`, which also defaulted to Colorful)
- The background color of external windows in the Colorful theme is White (`Theme.Background1` from `BaseColorfulColors.xaml`, which is set to `#FFFFFFFF`) as expected.
- Other hints that I can see that the Color Theme applied are the buttons and the checkboxes.

**Comment by iskandarzulkarnaien** [comment]
I'm testing it on 2013, there seems to be no changes when I change themes. I suspect there is a mismatch in ColorTheme IDs in ThemeManager.cs

White:
Actual Value: 0 (COLORFUL)
Expected Value: 5 (WHITE)

Light Gray: (the value is correct, but the color seems to not change? same behaviour as 2016 except that 2016 doesnt have a light gray option so i had to manually tweak the value to test)
Actual Value: 1 (LIGHT_GRAY)
Expected Value: 1 (LIGHT_GRAY)

Dark Gray:
Actual Value: 2 (DARK_GRAY_ALT, no changes in color)
Expected Value: 3 (DARK_GRAY) (im following 2016, where the dark gray setting results in value of 3)

**Comment by xantho09** [comment]
The XAML themes that I've added were the ones that were previously handled in the code (in `dev-release`), which are the Colorful/Default (ID=0), Dark Gray (ID=3), Black (ID=4) and White (ID=5) themes in 2016/2019.

The themes that have yet to be implemented are:
- 2010: Blue (ID = ?)
- 2010: Silver (ID = ?)
- 2010: Black (ID = ?)
- 2013: Light Gray (ID = 1)
- 2013: Dark Gray (ID = 2)

In those cases, the default `ColorfulTheme.xaml` will be used, which gives the panes their default appearance. Currently, I'm satisfied as long as none of the views crash in previous versions of PPT for those themes.

We can add these to the list of things left to do for ColorThemes, which I listed at the end of my initial PR message, then list them as an issue.

**Comment by iskandarzulkarnaien** [comment]
> 
> We can add these to the list of things left to do for ColorThemes, which I listed at the end of my initial PR message, then list them as an issue.

I'm alright with opening a separate issue to implement these changes. The missing themes mainly affect PPT2013

**Comment by iskandarzulkarnaien** [comment]
>
> I'm alright with opening a separate issue to implement these changes. The missing themes mainly affect PPT2013

Other than this, theres no issue with this PR for 2013
