### PR TITLE
PasteLab: Paste Into Group causes exceptions #1290 

### LINKED ISSUE #1290: PasteLab: Paste Into Group causes exceptions
(Win10 PowerPoint 2016 64-bit)

I got an uncaught exception when I try to "Paste Into Group" with two shapes selected.

I got another exception by "Paste into group" after selecting two textboxes (the blue shape appeared with the exception).

### PR DESCRIPTION
**Pull request by initialshl**
Fixes #1290 , #1336 , #1345 

- Show error message when trying to 'Convert To Picture' on title placeholders
- Disable 'Merge Into Group' and 'Paste Into Group' if a title placeholder is selected
- Fix exception for 'Paste Into Group' for multiple selection
  - 'Paste Into Group' now pastes correctly at the center of the selection
- Rewrote Paste Lab features to use existing util functions such as TransferAnimations
  - Only 'Paste To Cursor Position' will create a temporary slide and delete it
- Move MergeIntoGroup out of Paste Lab in code base

All tests passed on PPT 2016.

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/ActionFramework/Common/Interface/EnabledHandler.cs [hunk 1]
```diff
@@ -22,5 +24,26 @@ public bool Get(string ribbonId)
...
+                {
+                    return true;
+                }
+            }
+            return false;
+        }
+
+        // Allow ActionFrameworkExtensions to get current selection
+#pragma warning disable 0618
+        protected Selection GetCurrentSelection()
```
Comment (kai33) [inline PowerPointLabs/PowerPointLabs/ActionFramework/Common/Interface/EnabledHandler.cs]: try to avoid this?
e.g. make all kinds of handlers inherit a class like BaseHandler,
and edit extensions ([this one](https://github.com/initialshl/PowerPointLabs/blob/dev-release/PowerPointLabs/PowerPointLabs/ActionFramework/Common/Extension/BaseActionHandlerExtensions.cs)) for this BaseHandler to access the context

Comment (initialshl) [inline PowerPointLabs/PowerPointLabs/ActionFramework/Common/Interface/EnabledHandler.cs]: Ok done, thanks

**Comment by IanTeo** [comment]
[PasteLab.pptx](https://github.com/PowerPointLabs/PowerPointLabs/files/1000471/PasteLab.pptx)
Slide 23. For your reference

**Comment by initialshl** [comment]
Fixed the exceptions, also fixes #1336 exception with text in clipboard

**Comment by initialshl** [comment]
Thanks, these issues are now fixed

**Comment by IanTeo** [comment]
There is a weird bug that happens when I use Replace With Clipboard on a object in a group

File: PowerPointLabs/PowerPointLabs/PasteLab/PasteLabMain.cs [hunk 2]
```diff
@@ -66,123 +62,138 @@ public static void PasteToFillSlide(PowerPointSlide slide, bool clipboardIsEmpty
...
                 Logger.Log("PasteAndReplace: Replacing item in group");
-                shapeToReplace = selection.ChildShapeRange[1];
-                selection.ShapeRange[1].Select();
-                var pastedShapes = PasteIntoGroup(presentation, slide, clipboardIsEmpty, selection);
-                pastedShapes.Left = shapeToReplace.Left;
-                pastedShapes.Top = shapeToReplace.Top;
-                shapeToReplace.Delete();
+                selectedShape = selection.ChildShapeRange[1];
+                
+                Shape newGroup = PutIntoGroup(presentation, slide, selection.ShapeRange, pastingShapes, selectedShape.Left, selectedShape.Top);
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/PasteLabMain.cs]: MINOR Remove this unused 'newGroup' local variable. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1481)

**Comment by IanTeo** [comment]
Hmm.. the weird behavior still persists for images copied from outside powerpoint

**Comment by initialshl** [comment]
I rewrote the Paste Lab features for them to use the already implemented util function such as TransferAnimations instead of creating a temporary slide and copying them. Only Paste To Original Position will create a temporary slide due to limitations of native Paste.

The clipboard should only be accessed within Action Handlers, which pass in the pasted shapes as a parameter to the Paste Lab methods.

File: PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs [hunk 3]
```diff
@@ -0,0 +1,33 @@
+﻿using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.PasteLab
+{
+    class PasteToFillSlide
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/PasteLab/PasteIntoGroup.cs [hunk 4]
```diff
@@ -0,0 +1,67 @@
+﻿using System.Collections.Generic;
+
+using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.PasteLab
+{
+    class PasteIntoGroup
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/PasteIntoGroup.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/MiscFeatures/MergeIntoGroup.cs [hunk 5]
```diff
@@ -0,0 +1,23 @@
+﻿using System.Collections.Generic;
+
+using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.MiscFeatures
+{
+    class MergeIntoGroup
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/MiscFeatures/MergeIntoGroup.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/PasteLab/ReplaceWithClipboard.cs [hunk 6]
```diff
@@ -0,0 +1,46 @@
+﻿using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+
+namespace PowerPointLabs.PasteLab
+{
+    class ReplaceWithClipboard
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/ReplaceWithClipboard.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs [hunk 7]
```diff
@@ -0,0 +1,33 @@
+﻿using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.PasteLab
+{
+    internal class PasteToFillSlide
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/PasteToFillSlide.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/PasteLab/PasteIntoGroup.cs [hunk 8]
```diff
@@ -0,0 +1,67 @@
+﻿using System.Collections.Generic;
+
+using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.PasteLab
+{
+    internal class PasteIntoGroup
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/PasteIntoGroup.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/MiscFeatures/MergeIntoGroup.cs [hunk 9]
```diff
@@ -0,0 +1,23 @@
+﻿using System.Collections.Generic;
+
+using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+using PowerPointLabs.Utils;
+
+namespace PowerPointLabs.MiscFeatures
+{
+    internal class MergeIntoGroup
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/MiscFeatures/MergeIntoGroup.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)

File: PowerPointLabs/PowerPointLabs/PasteLab/ReplaceWithClipboard.cs [hunk 10]
```diff
@@ -0,0 +1,46 @@
+﻿using Microsoft.Office.Interop.PowerPoint;
+
+using PowerPointLabs.Models;
+
+namespace PowerPointLabs.PasteLab
+{
+    internal class ReplaceWithClipboard
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PasteLab/ReplaceWithClipboard.cs]: MAJOR Add a 'protected' constructor or the 'static' keyword to the class declaration. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS1118)
