### PR TITLE
Undoing Blur Selected on grouped items crashes PPT 2016 #1413 

### LINKED ISSUE #1413: Undoing Blur Selected on grouped items crashes PPT 2016
1. Select a grouped object / group of objects
1. Apply Effects Lab -> Blur Selected -> 40%
1. Undo (ctrl-z)

PPT will crash. This is very likely caused by grouped shapes being corrupted (limitations of PPT API).

Tested on PPT 2016
Does not crash PPT 2013

### PR DESCRIPTION
**Pull request by initialshl**
Fixes #1413 

Since this happens after an undo, we are unable to prevent this, so catching the exception is the best solution. The selection will be unselected when such exception occurs.

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs [hunk 1]
```diff
@@ -1,187 +1,187 @@
...
+
+        private static bool isInit = false;
+
+        private static PowerPoint.Selection selectedRange;
+
+        private static IntPtr slideViewWindowHandle;
+
+        private static Rectangle slideViewWindowRectangle;
+
+        private static Native.HookProc hookProcedure;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs]: MINOR Remove the 'hookProcedure' field and declare it as a local variable in the relevant methods. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1450)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs [hunk 2]
```diff
@@ -1,187 +1,187 @@
...
+            float y = Cursor.Position.Y;
+            return x > slideViewWindowRectangle.X 
+                && x < slideViewWindowRectangle.X + slideViewWindowRectangle.Width 
+                && y > slideViewWindowRectangle.Y 
+                && y < slideViewWindowRectangle.Y + slideViewWindowRectangle.Height;
+        }
+
+        //for Office 2010, its window structure is like MDIClient --> mdiClass --> paneClassDC (SlideView)
+        //but for Office 2013, it's like MDIClient --> mdiClass (SlideView)
+        //this structure can be found using SPY++ provided by visual studio
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs]: MAJOR Remove this commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS125)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs [hunk 3]
```diff
@@ -1,187 +1,187 @@
...
+using System.Runtime.InteropServices;
+using System.Text;
+using System.Windows.Forms;
+
+using PowerPointLabs;
+using PowerPoint = Microsoft.Office.Interop.PowerPoint;
+
+namespace PPExtraEventHelper
+{
+    internal class PPMouse
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPMouse.cs]: MINOR Rename class 'PPMouse' to match camel case naming rules, consider using 'PpMouse'. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS101)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 4]
```diff
@@ -1,143 +1,143 @@
...
+            }
+            else if (m.Msg == (int)Native.Message.WM_DRAWCLIPBOARD)
+            {
+                if (!isFirstTimeEnter)
+                {
+                    isCopyEvent = true;
+                }
+                else
+                {
+                    isFirstTimeEnter = false;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 5]
```diff
@@ -1,143 +1,143 @@
...
+        }
+
+        protected override void WndProc(ref Message m)
+        {
+            base.WndProc(ref m);
+            if (m.Msg == (int)Native.Message.WM_CHANGECBCHAIN)
+            {
+                if (m.WParam == nextHandle)
+                {
+                    nextHandle = m.LParam;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 6]
```diff
@@ -1,143 +1,143 @@
...
+                            AfterCopy(selectedRange);
+                        }
+                        else //PasteEvent
+                        {
+                            AfterPaste(selectedRange);
+                        }
+                        isCopyEvent = false;
+                    }
+                }
+                catch (Exception)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: MINOR Handle the exception or explain in a comment why it can be ignored. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2486)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 7]
```diff
@@ -1,143 +1,143 @@
...
+                        selectedRange = selection;
+                        if (!isSuccessful)
+                        {
+                            isSuccessful = Native.AddClipboardFormatListener(instance.Handle);
+                        }
+                    };
+                }
+                catch
+                {
+                    //TODO: support win XP?
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: INFO Complete the task associated to this 'TODO' comment. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1135)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 8]
```diff
@@ -1,143 +1,143 @@
...
+                        }
+                        else //PasteEvent
+                        {
+                            AfterPaste(selectedRange);
+                        }
+                        isCopyEvent = false;
+                    }
+                }
+                catch (Exception)
+                {
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: MAJOR Either remove or fill this block of code. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS108)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 9]
```diff
@@ -1,143 +1,143 @@
...
+        {
+            Native.ChangeClipboardChain(handle, nextHandle);
+            if (isSuccessful)
+            {
+                Native.RemoveClipboardFormatListener(handle);
+            }
+            base.Dispose(disposing);
+        }
+
+        protected override void WndProc(ref Message m)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 18 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS3776)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 10]
```diff
@@ -1,143 +1,143 @@
...
+                else
+                {
+                    Native.SendMessage(nextHandle, (uint)m.Msg, m.WParam, m.LParam);
+                }
+            }
+            else if (m.Msg == (int)Native.Message.WM_DRAWCLIPBOARD)
+            {
+                if (!isFirstTimeEnter)
+                {
+                    isCopyEvent = true;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: CRITICAL Remove this set, which updates a 'static' field from an instance method. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2696)

File: PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs [hunk 11]
```diff
@@ -1,143 +1,143 @@
...
+using System.ComponentModel;
+using System.Diagnostics;
+using System.Linq;
+using System.Text;
+using System.Windows.Forms;
+using PowerPoint = Microsoft.Office.Interop.PowerPoint;
+
+namespace PPExtraEventHelper
+{
+    internal class PPCopy : Control
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/PPExtraEventHelper/PPCopy.cs]: MINOR Rename class 'PPCopy' to match camel case naming rules, consider using 'PpCopy'. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS101)

**Comment by initialshl** [comment]
These SonarQube issues are reported for old code (due to moving the files), which will be refactored in future (and ignored for now).
