### PR TITLE
Fix #592 Text highlight is behind the text

### LINKED ISSUE #592: Text highlight is behind the text
Highlight test does not work if the text box has a fill color. Perhaps in such cases the highlight should be in front of the text?

### PR DESCRIPTION
**Pull request by LIUJIAHAOCS**
Use Transparency instead of comparing forecolor

### CODE REVIEW

**Comment by LIUJIAHAOCS** [comment]
image
The highlight will look like this.

File: PowerPointLabs/PowerPointLabs/HighlightTextFragments.cs [hunk 1]
```diff
@@ -107,8 +107,9 @@ private static List<PowerPoint.Shape> GetShapesToAnimate(PowerPointSlide current
 
         private static List<PowerPoint.Shape> GetShapesFromLinesInText(PowerPointSlide currentSlide, Office.TextRange2 text, PowerPoint.Shape shape)
         {
-            List<PowerPoint.Shape> shapesToAnimate = new List<PowerPoint.Shape>();
-
+            List<PowerPoint.Shape> shapesToAnimate = new List<PowerPoint.Shape>();
+            Boolean isHasBackground = (shape.Fill.Transparency).CompareTo(1.0f) == 0;
```
Comment (kai33) [inline PowerPointLabs/PowerPointLabs/HighlightTextFragments.cs]: the variable name is not good enough.
maybe isTextBoxTransparent
