### PR TITLE
Paste Into Group has exception after undo #1370 

### LINKED ISSUE #1370: Paste Into Group has exception after undo
Paste Into Group throws an uncaught exception if I paste, undo and paste again

### PR DESCRIPTION
**Pull request by initialshl**
Fixes #1370 

Paste Lab exceptions that are caused by corrupted shapes after undo action is now fixed.
Needs to be tested on PPT 2010/2013. PPT 2016 has less exception occurrences. 

Special thanks to @IanTeo for the solution!

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs [hunk 1]
```diff
@@ -12,6 +12,9 @@ namespace PowerPointLabs.ActionFramework.Action.PasteLab
 {
     abstract class PasteLabActionHandler : BaseUtilActionHandler
     {
+        private static readonly string SelectOrderTagName = "SelectOrderTagName";
+        private static readonly string SelectChildOrderTagName = "SelectChildOrderTagName";
+
         // Sealed method: Subclasses should override ExecutePasteAction instead
         protected sealed override void ExecuteAction(string ribbonId)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 28 to the 15 allowed. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS3776)

File: PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs [hunk 2]
```diff
@@ -12,6 +12,9 @@ namespace PowerPointLabs.ActionFramework.Action.PasteLab
 {
     abstract class PasteLabActionHandler : BaseUtilActionHandler
     {
+        private static readonly string SelectOrder = "PasteLabSelectOrder";
+        private static readonly string SelectChildOrder = "PasteLabSelectChildOrder";
+
         // Sealed method: Subclasses should override ExecutePasteAction instead
         protected sealed override void ExecuteAction(string ribbonId)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 28 to the 15 allowed. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS3776)

File: PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs [hunk 3]
```diff
@@ -12,6 +12,9 @@ namespace PowerPointLabs.ActionFramework.Action.PasteLab
 {
     abstract class PasteLabActionHandler : BaseUtilActionHandler
     {
+        private static readonly string SelectOrderTagName = "PasteLabSelectOrder";
+        private static readonly string SelectChildOrderTagName = "PasteLabSelectChildOrder";
+
         // Sealed method: Subclasses should override ExecutePasteAction instead
         protected sealed override void ExecuteAction(string ribbonId)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/ActionFramework/Action/PasteLab/PasteLabActionHandler.cs]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 16 to the 15 allowed. [rule](https://sonarqube.com/coding_rules#rule_key=csharpsquid%3AS3776)
