### PR TITLE
#1606 Fix pasting of web pictures

### LINKED ISSUE #1380: Paste Lab exception when clipboard has Slide objects
When the clipboard has an entire slide copied, using Paste Lab features will cause an exception.

capture

### LINKED ISSUE #1606: Paste Lab Error: PPT2013 PasteShapeFromClipboard method does not work
error

Steps to replicate:
1. Run PowerPoint 2013
2. Copy any image from the browser
3. Right-click and try to activate any PasteLab function

Exceptions:
Upon some tinkering, it was found that if you follow steps 1 & 2, but then instead of using PPTLabs directly, you default-copy into the slide first, copy/cut that image again, and then use the PasteLab functions, it will work.

I think it when the image is copied from the browser, the image is not registered in the clipboard or not read properly from the code. Only works for me when I re-copy/cut the image from inside PPT2013 again.

No problems for PPT2016 though.

@alexfjw @leeyh20 would need your help to check if this is the case on your versions of PPT2013 as well.

### PR DESCRIPTION
**Pull request by leeyh20**
Resolves #1606 which will allow web pictures to be pasted with all the Paste Lab functions without errors being thrown.

Side effect: This also resolves #1380 because it will paste slide objects as a picture instead.

Also changes RestoreClipboardAfterAction for web pictures in clipboard because it will now try to paste as a PNG picture, then bitmap picture and then try View.Paste(). The benefits of trying to paste as PNG picture is that the transparency of the picture will not be lost in case it is a PNG picture.

To test web pictures with RestoreClipboardAfterAction, use ConvertToPicture with web pictures in the clipboard.

To Test: 
1. Paste Lab functions with web pictures in clipboard (can try PNG pictures)
2. Paste Lab functions with slide objects in clipboard
3. ConvertToPicture with web pictures in clipboard (can try PNG pictures)

There is a weird powerpoint bug where sometimes it cannot detect that the web picture it is pasting is a PNG picture until I try to paste it using the clipboard pane first. This seems to be a problem with powerpoint itself because even the default paste / paste special does not allow me to paste the web picture as PNG. Thus in this case, Paste Lab will just have to paste it as bitmap picture (without transparency) :(

### CODE REVIEW

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 1]
```diff
@@ -200,11 +212,25 @@ private static ShapeRange TryPastingAsShape(PowerPointSlide slide)
...
+            try
+            {
+                // try pasting as picture
+                return PasteWithCorrectSlideCheck(slide, true, PpPasteDataType.ppPasteBitmap);
+            }
+            catch (COMException e)
+            {
+                // May be thrown if clipboard is not a picture
+                Logger.LogException(e, "TryPastingAsPicture");
+                return null;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Return an empty collection instead of null. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1168)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 2]
```diff
@@ -200,11 +212,25 @@ private static ShapeRange TryPastingAsShape(PowerPointSlide slide)
...
+            }
+        }
         /// <summary>
         /// Pastes clipboard content into new temp slide using the DocumentWindow's View.Paste()
         /// Though this paste will work for most clipboard objects (even web pictures), it will change the undo history.
         /// </summary>
-        private static Shape TryPastingOntoView(PowerPointPresentation pres, PowerPointSlide tempSlide, PowerPointSlide origSlide)
+        private static Shape TryPastingOntoView(PowerPointPresentation pres, PowerPointSlide tempSlide, PowerPointSlide origSlide = null)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Remove the unused private method 'TryPastingOntoView'. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1144)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs (hunk 1 above)
Comment (leeyh20) [reply PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: Need to return null because ShapeRange cannot be empty

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 3]
```diff
@@ -19,20 +19,39 @@ public static bool IsClipboardEmpty()
...
+                    }
+                    return picture;
+                }
             }
             catch (COMException e)
             {
                 // May be thrown if there is placeholder shape in clipboard
-                Logger.LogException(e, "PasteShapeFromClipboard");
+                Logger.LogException(e, "PasteShapesFromClipboard");
                 return null;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Return an empty collection instead of null. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1168)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 4]
```diff
@@ -199,12 +227,25 @@ private static ShapeRange TryPastingAsShape(PowerPointSlide slide)
...
+            }
+            catch (COMException e)
+            {
+                // May be thrown if clipboard is not a PNG picture
+                Logger.LogException(e, "TryPastingAsPNG");
+                return null;
+            }
+        }
         /// <summary>
         /// Pastes clipboard content into new temp slide using the DocumentWindow's View.Paste()
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Remove the unused private method 'TryPastingAsBitmap'. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1144)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 5]
```diff
@@ -19,20 +19,42 @@ public static bool IsClipboardEmpty()
...
+                    // Try to get enumerator and sees if it throws an error
+                    // Will throw error if its a web picture
+                    shapes.GetEnumerator();
+                    return shapes;
+                }
+                catch (COMException e)
+                {
+                    Logger.LogException(e, "PasteShapesFromClipboard");
+                    // Delete previously pasted "shapes" because it is not a valid shape
+                    if (shapes != null)
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Change this condition so that it does not always evaluate to 'false'; some subsequent code is never executed. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS2583)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 6]
```diff
@@ -19,20 +19,42 @@ public static bool IsClipboardEmpty()
...
+                    }
+                    return picture;
+                }
             }
             catch (COMException e)
             {
                 // May be thrown if there is placeholder shape in clipboard
-                Logger.LogException(e, "PasteShapeFromClipboard");
+                Logger.LogException(e, "PasteShapesFromClipboard");
                 return null;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Return an empty collection instead of null. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1168)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 7]
```diff
@@ -199,12 +239,41 @@ private static ShapeRange TryPastingAsShape(PowerPointSlide slide)
...
+            try
+            {
+                // try pasting as PNG picture to preserve transparency
+                return PasteWithCorrectSlideCheck(slide, true, PpPasteDataType.ppPastePNG);
+            }
+            catch (COMException e)
+            {
+                // May be thrown if clipboard is not a PNG picture
+                Logger.LogException(e, "TryPastingAsPNG");
+                return null;
```
Comment (PPTLabsBot) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: MAJOR Return an empty collection instead of null. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS1168)

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs (hunk 5 above)
Comment (leeyh20) [reply PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: Subsequent code will be executed if the COMException is caught, which is the case when web pictures are being pasted.

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs (hunk 6 above)
Comment (leeyh20) [reply PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: ShapeRange cannot be empty

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs (hunk 7 above)
Comment (leeyh20) [reply PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: ShapeRange cannot be empty

**Comment by leeyh20** [comment]
@alexfjw Thanks for testing, somehow ConvertToPicture manages to restore the clipboard with web pictures for my computer, so maybe its really a computer-dependent issue....

**Comment by leeyh20** [comment]
I have added a few more commits to support pasting on my PPT 2010.

**Comment by junkiattan** [comment]
@alexfjw 

 tested on my PPT2016. The code works fine and is as Alex said.

However 2013 had multiple issues. In the list of to-tests, it seems that only no 2 works. 

1. When trying to paste any web pictures via the Paste Lab function, the follwing error appears for all paste lab functions

below screenshot was when I tried to "PasteToFill"
error1

3. Convert to picture strangely replaces the clipboard for web images, and also for any shapes in the current "head" position of the clipboard

**Comment by alexfjw** [comment]
I've re-tested the PasteLab features on 2013. They seem to work well on my side. (excluding the thing about ConvertToPicture)
@junkiattan Could you reconfirm on your side as well just to make sure? 
We should flag this as in intermittent problem if it still doesn't work for you.
Thanks.

**Comment by leeyh20** [comment]
@junkiattan Ok I believe that on 2013, the paste lab functions work well now.

**Comment by leeyh20** [comment]
Re-tested on 2010 and it works.

**Comment by initialshl** [comment]
Is this ready for review? Are the final tests passing?

**Comment by leeyh20** [comment]
@initialshl Yup it is ready for review. The tests  (that uses Shapes) are definitely passing but Convert To Picture restoring clipboard with web pictures is not working for Alex’s computer but I cannot reproduce the issue on my two other computers...

**Comment by leeyh20** [comment]
We have been testing web pictures manually because it requires a copy and paste from a website like google search directly.

**Comment by leeyh20** [comment]
@initialshl We have been testing web pictures manually because it requires copying a picture from a website like google search directly and the tests use powerpoint shapes.

File: PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFillSlide/PasteToFillSlideActionHandler.cs [hunk 8]
```diff
@@ -14,7 +14,7 @@ class PasteToFillSlideActionHandler : PasteLabActionHandler
         protected override ShapeRange ExecutePasteAction(string ribbonId, PowerPointPresentation presentation, PowerPointSlide slide,
                                                         ShapeRange selectedShapes, ShapeRange selectedChildShapes)
         {
-            ShapeRange pastingShapes = ClipboardUtil.PasteShapesFromClipboard(slide);
+            ShapeRange pastingShapes = ClipboardUtil.PasteShapesFromClipboard(presentation, slide);
             if (pastingShapes == null)
             {
                 return null;
```
Comment (initialshl) [inline PowerPointLabs/PowerPointLabs/ActionFramework/PasteLab/PasteToFillSlide/PasteToFillSlideActionHandler.cs]: Does hitting this block mean that an error occurred and so nothing happened? Maybe you could log it/show error message. Similarly for others.

File: PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs [hunk 9]
```diff
@@ -215,11 +282,21 @@ private static Shape TryPastingOntoView(PowerPointPresentation pres, PowerPointS
...
+                if (origSlide != null)
+                {
+                    pres.GotoSlide(origSlide.Index);
+                }
+
                 int finalShapesCount = tempSlide.Shapes.Count;
                 if (finalShapesCount > origShapesCount) 
                 {
-                    return tempSlide.Shapes.Range()[finalShapesCount];
+                    int newShapesNo = finalShapesCount - origShapesCount;
```
Comment (initialshl) [inline PowerPointLabs/PowerPointLabs/Utils/ClipboardUtil.cs]: Think its better to call it newShapesCount/newShapesNumber/newShapesNum?
