### PR TITLE
#1918 UI bug in E-Learning Lab: Text overflow cannot scroll

### LINKED ISSUE #1918: UI bug in E-Learning Lab: Text overflow cannot scroll
image

PPT2016, Win10

The name for the audio does not display fully and cannot be scrolled.

Suggested fix:
Wrap the text when the name overflows.

### PR DESCRIPTION
**Pull request by daekoon**
Fixes #1918 

**Outline of Solution**
Fixed the issue by making the name wrap if it overflows, as suggested in the issue tracker.
One problem faced while implementing this solution was that in order for the TextBlock to wrap, its width cannot be set to automatic. To circumvent this, I made the grid's column inherit the width of the ListView, and created a simple converter that subtracts 45 pixels from the value given. (45 pixels is the size of the icon on the left)

### CODE REVIEW

**Comment by daekoon** [comment]
There seems to be a problem with the SonarQube during integration.

**Comment by yuhongherald** [comment]
Noted the problem with SonarQube, will be trying to diagnose the problem.

File: PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+namespace PowerPointLabs.ELearningLab.Converters
+{
+    public class ShapeNameWidthConverter : IValueConverter
+    {
+        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
+        {
+            if (value is double)
+            {
+                return (double)value - 45;
```
Comment (yuhongherald) [inline PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs]: 45 is a constant that is used multiple times, you can declare a constant locally.

File: PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs [hunk 2]
```diff
@@ -0,0 +1,28 @@
+﻿using System;
+using System.Text.RegularExpressions;
```
Comment (yuhongherald) [inline PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs]: Unused import directives should be removed.

File: PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs (hunk 1 above)
Comment (daekoon) [reply PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs]: Replaced constant with a local constant

File: PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs (hunk 2 above)
Comment (daekoon) [reply PowerPointLabs/PowerPointLabs/ELearningLab/Converters/ShapeNameWidthConverter.cs]: Removed unused directive

**Comment by yuhongherald** [comment]
Great! Tested on PPT2013 and it works.
